# *******************************************************************************
# Copyright (c) 2019 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
# *******************************************************************************
openapi: "3.0.2"
info:
  title: Validation API
  version: "1.0"
  description: Tests the basic configuration of resources by attempting to perform a simple operation on them.
servers:
  - url: https://127.0.0.1:8020/ibm/api
paths:
  /validation/dataSource/{uid}:
    get:
      tags:
      - Validation
      summary: Validation of a Data Source
      description: "Retrieves the validation result for the specified data source. Validation involves establishing a connection to the database, querying basic metadata information, and performing the `java.sql.Connection.isValid` operation."
      parameters:
        - name: uid
          in: path
          description: "**Unique identifier**. For a data source configured at top level, this is the value of the `id` attribute, if present. Otherwise, it is a generated value, such as *databaseStore[defaultDatabaseStore]/dataSource[default-0]*."
          required: true
          schema:
            type: string
            example: DefaultDataSource
          examples:
            example-ds-id:
              summary: "Top-level dataSource with id"
              description: "The default data source is configured at top-level and has an id of DefaultDataSource."
              value: "DefaultDataSource"
            example-ds-no-id:
              summary: "Top-level dataSource without id"
              description: "A generated uid for top-level data sources which lack an id is computed based on the order of appearance within server config, starting at 0."
              value: "dataSource[default-0]"
            example-ds-nested:
              summary: "Nested dataSource without id"
              description: "References the first dataSource (index 0) that is nested under the databaseStore element with id of defaultDatabaseStore."
              value: "databaseStore[defaultDatabaseStore]/dataSource[default-0]"
            example-ds-nested-under-singleton:
              summary: "Nested dataSource (without id) under singleton"
              description: "References the first dataSource (index 0) that is nested under the transaction element. The transaction element is a singleton and cannot have an id."
              value: "transaction/dataSource[default-0]"
            example-ds-app-def:
              summary: "App-defined data source"
              description: "References a data source defined by @DataSourceDefinition within the MyApp application, in the MyWebModule module, with a name of java:module/env/jdbc/ds1"
              value: "application[MyApp]/module[MyWebModule]/dataSource[java:comp/module/env/jdbc/ds1]"
        - name: X-Validation-User
          in: header
          description: "**User**. Supplies a user name when not using Container-managed authentication."
          schema:
            type: string
        - name: X-Validation-Password
          in: header
          description: "**Password**. Supplies a password when not using Container-managed authentication."
          schema:
            type: string
            format: password
        - name: auth
          in: query
          description: "**Authentication**. Determines whether to use a resource reference with Application-managed or Container-managed authentication, or no resource reference."
          schema:
           type: string
           enum:
             - application
             - container
        - name: authAlias
          in: query
          description: "**Authentication Alias**. Supplies the `id` of an `authData` to use for Container-managed authentication."
          schema:
            type: string
        - name: loginConfig
          in: query
          description: "**Custom Login**. Supplies the `name` of a `jaasLoginContextEntry` to use for Container-managed authentication."
          schema:
            type: string
# requestBody in GET will be allowed again in a newer version of OpenAPI
# see https://github.com/OAI/OpenAPI-Specification/pull/1937
#      requestBody:
#        description: "Additional details for request, including **Login Config Properties**"
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                loginConfigProperties:
#                  type: object
#                  additionalProperties:
#                    type: string
#              example:
#                loginConfigProperties:
#                  loginProp1: val1
#                  loginProp2: val2
      responses:
        200:
          description: Validation result retrieved
          content:
            application/json:
              schema:
                type: object
